name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Build
        run: |
          cd frontend
          npm install
          npm run build
      - name: Archive static asset files
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: frontend/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-built static files
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Clear server's static assets
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "if [ -d "~/.cdocker/vlm/me" ] ; then rm -rf ~/.cdocker/vlm/me ; fi"
      - name: Upload built static files
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ~/.cdocker/vlm/me"
          scp dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/web/.cdocker/vlm/me/
